
# Map creature type http://jd.bukkit.org/apidocs/org/bukkit/entity/CreatureType.html
# to entity ID http://www.minecraftwiki.net/wiki/Data_values#Entity_IDs
eggs:
    Creeper: 
        entityID: 50
    Skeleton: 
        entityID: 51
    Spider: 
        entityID: 52
    Giant: 
        entityID: 53
    Zombie: 
        entityID: 54
    Slime: 
        entityID: 55
    Ghast: 
        entityID: 56
    PigZombie: 
        entityID: 57
    Enderman: 
        entityID: 58
    CaveSpider: 
        entityID: 59
    Silverfish: 
        entityID: 60
    Blaze: 
        entityID: 61
    LavaSlime: 
        entityID: 62
    EnderDragon:
        entityID: 63
    Pig: 
        entityID: 90
    Sheep: 
        entityID: 91
    Cow: 
        entityID: 92
    Chicken: 
        entityID: 93
    Squid: 
        entityID: 94
    Wolf: 
        entityID: 95
    MushroomCow: 
        entityID: 96
    SnowMan: 
        entityID: 97
    Villager: 
        entityID: 120
    #monster:
