# See documentation at http://dev.bukkit.org/server-mods/silkspawners/

consumeEgg: true
usePermissions: false
useWorldGuard: true
defaultCreature: null
spawnerCommandReachDistance: 6

minSilkTouchLevel: 1

destroyDropEgg: false
#destroyDropEgg: true
destroyDropXP: 0
#destroyDropXP: 1000
destroyDropBars: 0
#destroyDropBars: 8

craftableSpawners: false
spawnersUnstackable: false

verboseConfig: false
spawnEggOverride: false
dumpEntityMap: false

useSpout: true
notifyOnClick: true
notifyOnHold: true

# creatures: key is official creature type name, case-sensitive, from http://jd.bukkit.org/apidocs/org/bukkit/entity/CreatureType.html
# entityID is used in spawn eggs, from http://www.minecraftwiki.net/wiki/Data_values#Entity_IDs
creatures:
    Creeper: 
        aliases: ['c', 'creep', 'cataclysm']
        enableCraftingSpawner: true
    Skeleton: 
        aliases: ['s', 'sk', 'skelly', 'skellington']
        enableCraftingSpawner: true
    Spider: 
        aliases: ['sp', 'bug']
        enableCraftingSpawner: true
    Giant: 
        aliases: ['giantzombie']
        enableCraftingSpawner: true
    Zombie: 
        aliases: ['z']
        enableCraftingSpawner: true
    Slime: 
        aliases: ['sl']
        enableCraftingSpawner: true
    Ghast: 
        aliases: ['g']
        enableCraftingSpawner: true
    PigZombie: 
        aliases: ['pigman', 'zombiepigman', 'pg', 'zp']
        displayName: 'Zombie Pigman'
        enableCraftingSpawner: true
    Enderman: 
        aliases: ['e', 'ender', 'endermen', 'slenderman']
        enableCraftingSpawner: true
    CaveSpider: 
        aliases: ['cspider', 'cs', 'bluespider']
        displayName: 'Cave Spider'
        enableCraftingSpawner: true
    Silverfish: 
        aliases: ['sf', 'fish']
        enableCraftingSpawner: true
    Blaze: 
        aliases: ['b']
        enableCraftingSpawner: true
    LavaSlime: 
        aliases: ['magmacube', 'mcube', 'magma', 'm', 'mc']
        displayName: 'Magma Cube'
        enableCraftingSpawner: true
    EnderDragon:
        displayName: 'Enderdragon'
        aliases: ['dragon', 'raqreqentba']
        enableCraftingSpawner: true
    Pig: 
        aliases: ['p']
        enableCraftingSpawner: true
    Sheep: 
        aliases: ['sh']
        enableCraftingSpawner: true
    Cow: 
        aliases: ['bovine']
        enableCraftingSpawner: true
    Chicken: 
        aliases: ['chick', 'ch', 'bird']
        enableCraftingSpawner: true
    Squid: 
        aliases: ['sq', 'octopus']
        enableCraftingSpawner: true
    Wolf: 
        aliases: ['w', 'dog']
        enableCraftingSpawner: true
    MushroomCow: 
        displayName: 'Mooshroom'
        aliases: ['m', 'mcow']
        enableCraftingSpawner: true
    SnowMan: 
        displayName: 'Snow Golem'
        aliases: ['golem', 'sgolem', 'sg', 'sm', 'snowmen']
        enableCraftingSpawner: true
    Ozelot:
        displayName: 'Ocelot'
        aliases: ['ocelot', 'oce', 'o', 'cat', 'kitty']
        enableCraftingSpawner: true
    VillagerGolem:
        displayName: 'Iron Golem'
        aliases: ['igolem', 'ironman', 'iron', 'ig']
        enableCraftingSpawner: true
    Villager: 
        aliases: ['npc', 'v']
        enableCraftingSpawner: true
   
    # Modded mobs - if you're using 'useExtraMobs: true', comment/uncomment lines below as needed

    # Animal Bikes mod for MCPC 1.2.3 from http://www.mcportcentral.co.za/index.php?topic=1692.0
    # and http://www.minecraftforum.net/topic/762794-124-animal-bikes-v1111-sspsmp-added-iron-golem/
    # IMPORTANT: You have to mod your client and server as above before this will work.
    EntityCowBike:
        displayName: 'Cow Bike'
        aliases: ['cbike', 'cowb']
        enableCraftingSpawner: true
    EntitySpiderBike:
        displayName: 'Spider Bike'
        aliases: ['sbike', 'spbike', 'spiderb']
        enableCraftingSpawner: true
    EntityPigBike:
        displayName: 'Pig Bike'
        aliases: ['pbike', 'pigb']
        enableCraftingSpawner: true
    EntitySheepBike:
        displayName: 'Sheep Bike'
        aliases: ['shbike', 'sheepb']
        enableCraftingSpawner: true
    EntityChickenBike:
        displayName: 'Chicken Bike'
        aliases: ['chbike', 'chickenb']
        enableCraftingSpawner: true
    EntityWolfBike:
        displayName: 'Wolf Bike'
        aliases: ['wbike', 'wolfb']
        enableCraftingSpawner: true
    EntitySquidBike:
        displayName: 'Squid Bike'
        aliases: ['sqbike', 'squidb']
        enableCraftingSpawner: true
    EntityCreeperBike:
        displayName: 'Creeper Bike'
        aliases: ['crbike', 'creeperb']
        enableCraftingSpawner: true
    EntityPonyBike:
        displayName: 'Pony Bike'
        aliases: ['pobike', 'ponyb', 'pony', 'horse']
        enableCraftingSpawner: true
    EntityEndermanBike:
        displayName: 'Enderman Bike'
        aliases: ['ebike', 'enderb', 'endermanb', 'enderbike']
        enableCraftingSpawner: true
    EntityDragonBike:
        displayName: 'Dragon Bike'
        aliases: ['dbike', 'dragonb']
        enableCraftingSpawner: true
    EntityNotchBike:
        displayName: 'Notch Bike'
        aliases: ['nbike', 'notchb', 'notch']
        enableCraftingSpawner: true
    EntityReindeerBike:
        displayName: 'Reindeer Bike'
        aliases: ['rbike', 'reindeerb', 'reindeer', 'deer']
        enableCraftingSpawner: true
    EntitySnowGolemBike:
        displayName: 'Snow Golem Bike'
        aliases: ['sgbike', 'snowbike', 'snowgolemb', 'sgolemb', 'snowgollembike', 'snowgolembike']
        enableCraftingSpawner: true
    EntityGhastBike:
        displayName: 'Ghast Bike'
        aliases: ['gbike', 'ghastb']
        enableCraftingSpawner: true
    EntityIronmanBike:
        displayName: 'Iron Golem Bike'
        aliases: ['igbike', 'irongolemb', 'igolemb']
        enableCraftingSpawner: true

    # Natural Selection mod for CraftBukkit 1.1-R4 from http://www.mcportcentral.co.za/index.php?topic=1360.0
    # and http://www.minecraftforum.net/topic/950329-110smpforgenatural-selection-a-minecraft-survival-accession-v21/
    # IMPORTANT: You have to mod your client and server as above before this will work.
#    Buck:
#        aliases: ['maledeer', 'mdeer']
#        enableCraftingSpawner: true
#    Doe:
#        aliases: ['femaledeer', 'fdeer', 'deer']
#        enableCraftingSpawner: true
#    Tom:
#        aliases: ['maleturkey', 'mturkey']
#        enableCraftingSpawner: true
#    Hen:
#        aliases: ['femaleturkey', 'fturkey', 'turkey']
#        enableCraftingSpawner: true
#    Grizzly:
#        aliases: ['bear']
#        enableCraftingSpawner: true
#    Boar:
#        aliases: ['wildpig']
#        enableCraftingSpawner: true
#    Dingo:
#        enableCraftingSpawner: true
#    Magicman:
#        aliases: ['magician']
#        enableCraftingSpawner: true

    # Rancraft Penguins 1.2.5f mod for CraftBukkit 1.2.5 from http://www.mcportcentral.co.za/index.php?topic=2491.0
    # and http://www.minecraftforum.net/topic/910095-125-rancraft-penguins-seven-species-mlmp-forge-bukkit/
    # IMPORTANT: You have to mod your client and server as above before this will work.
    Little Blue Penguin:
        aliases: ['lbpenguin', 'lpenguin', 'littlepenguin', 'bluepenguin', 'bpenguin', 'littleblue', 'lbp', 'lp']
        enableCraftingSpawner: true
    Flame Penguin:
        aliases: ['fpenguin', 'fp']
        enableCraftingSpawner: true
    King Penguin:
        aliases: ['kpenguin', 'kp']
        enableCraftingSpawner: true
    Yellow-Eyed Penguin:
        aliases: ['ypenguin', 'yp']
        enableCraftingSpawner: true
    Magellanic Penguin:
        aliases: ['mpenguin', 'mp']
        enableCraftingSpawner: true
    Adelie Penguin:
        #entityID: 21        # interestingly, this is the same as FallingSand.. but it doesn't seem to conflict(?)
        aliases: ['apenguin', 'ap']
        enableCraftingSpawner: true
    Emperor Penguin:
        aliases: ['epenguin', 'emperor', 'ep', 'penguin', 'peng']
        enableCraftingSpawner: true
