name: SilkSpawners
main: me.exphc.SilkSpawners.SilkSpawners
version: 0.1
commands:
    spawner:
        description: Change or view the monster spawner creature type
        usage: /<command> [creature]
permissions:
    silkspawners.*:
        children:
            silkspawners.info: true
            silkspawners.silkdrop: true
            silkspawners.eggdrop: true
            silkspawners.viewtype: true
            silkspawners.changetype: true
            silkspawners.freeitem: true
        default: false
    silkspawners.info:
        description: Allows you to see informative messages about the spawners as you place and break them
        default: true
    silkspawners.silkdrop:
        description: Allows you to use silk touch to acquire mob spawner items
        default: true
    silkspawners.eggdrop:
        description: Allows you to destroy mob spawners to acquire mob spawn eggs
        default: true
    silkspawners.viewtype:
        description: Allows you to view the spawner type using /spawner
        default: true
    silkspawners.changetype:
        description: Allows you to change the spawner type using /spawner [creature]
        default: op
    silkspawners.freeitem:
        description: Allows you to get spawner items in your hand for free using /spawner [creature]
