name: SilkSpawners
author: xGhOsTkiLLeRx
authors: [mushroomhostage]
main: de.dustplanet.silkspawners.SilkSpawners
version: ${project.version}-b${BUILD_NUMBER}
url: http://dev.bukkit.org/server-mods/silkspawners/
description: pick up and move monster spawners using silk touch
commands:
    silkspawners:
        aliases: [silkspawner, ss, spawner, silk, spawnersilk]
        description: Change or view the monster spawner creature type
        usage: /<command> [creature]|[creature]egg|all|reload
    egg:
        aliases: [eggs, eg]
        description: Change the egg type
        usage: /<command> [creature]|[creature]egg|all|reload
permissions:
    silkspawners.*:
        children:
            silkspawners.info: true
            silkspawners.viewtype: true
            silkspawners.reload: true
            silkspawners.explodedrop: true
            silkspawners.free: true
            silkspawners.createshop: true
            silkspawners.destroyshop: true
            silkspawners.silkdrop.*: true
            silkspawners.destroydrop.*: true
            silkspawners.changetype.*: true
            silkspawners.changetypewithegg.*: true
            silkspawners.freeitem.*: true
            silkspawners.freeitemegg.*: true
            silkspawners.craft.*: true
            silkspawners.place.*: true
        default: false
    silkspawners.info:
        description: Allows you to see informative messages about the spawners as you place and break them
        default: false
    silkspawners.viewtype:
        description: Allows you to view the spawner type using /spawner
        default: false
    silkspawners.reload:
        description: Allows you to reload the plugin
        default: false
    silkspawners.explodedrop:
        description: Allows you to receive drops on explosion
        default: false
softdepend: [WorldGuard, BarAPI]
